packages:
  - tests/fixtures/*

strictPeerDependencies: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
engineStrict: true
minimumReleaseAge: 1440 # 1 day

overrides:
  rolldown: 1.0.0-beta.45

catalogs:
  dev:
    "@eslint/config-inspector": 1.3.0
    "@types/node": 22.18.12
    "@typescript-eslint/rule-tester": 8.46.2
    eslint-typegen: 2.3.0
    jiti: 2.6.1
    tsdown: 0.15.12
    tsx: 4.20.6
    typescript: 5.9.3
    vitest: 4.0.5

  peer:
    "@eslint-react/eslint-plugin": 2.2.4
    "@unocss/eslint-plugin": 66.5.4
    astro-eslint-parser: 1.2.2
    eslint: 9.38.0
    eslint-plugin-astro: 1.4.0
    eslint-plugin-erasable-syntax-only: 0.3.1
    eslint-plugin-format: 1.0.2
    eslint-plugin-react-hooks: 7.0.1
    eslint-plugin-react-refresh: 0.4.24
    eslint-plugin-tailwindcss: 3.18.0
    prettier-plugin-astro: 0.14.1
    tailwindcss: 3.4.18
    unocss: 66.5.4
    vue: 3.5.22

  prod:
    "@antfu/install-pkg": 1.1.0
    "@clack/prompts": 0.11.0
    "@eslint-community/eslint-plugin-eslint-comments": 4.5.0
    "@eslint/markdown": 7.5.0
    "@stylistic/eslint-plugin": 5.5.0
    "@typescript-eslint/eslint-plugin": 8.46.2
    "@typescript-eslint/parser": 8.46.2
    "@vitest/eslint-plugin": 1.4.0
    eslint-config-flat-gitignore: 2.1.0
    eslint-flat-config-utils: 2.1.4
    eslint-merge-processors: 2.0.0
    eslint-plugin-antfu: 3.1.1
    eslint-plugin-command: 3.3.1
    eslint-plugin-import-lite: 0.3.0
    eslint-plugin-jsdoc: 61.1.11
    eslint-plugin-jsonc: 2.21.0
    eslint-plugin-n: 17.23.1
    eslint-plugin-perfectionist: 4.15.1
    eslint-plugin-pnpm: 1.3.0
    eslint-plugin-regexp: 2.10.0
    eslint-plugin-toml: 0.12.0
    eslint-plugin-unicorn: 62.0.0
    eslint-plugin-unused-imports: 4.3.0
    eslint-plugin-vue: 10.5.1
    eslint-plugin-yml: 1.19.0
    eslint-processor-vue-blocks: 2.0.0
    globals: 16.4.0
    jsonc-eslint-parser: 2.4.1
    local-pkg: 1.1.2
    parse-gitignore: 2.0.0
    toml-eslint-parser: 0.10.0
    vue-eslint-parser: 10.2.0
    yaml-eslint-parser: 1.3.0

onlyBuiltDependencies:
  - esbuild
