packages:
  - tests/fixtures/*

overrides:
  "@eslint-community/eslint-utils": ^4.7.0
  "@typescript-eslint/utils": ^8.34.1
  eslint: ^9.29.0
  tsx: ^4.20.3

catalogs:
  dev:
    "@eslint/config-inspector": ^1.1.0
    "@types/node": ^22.13.10
    "@typescript-eslint/rule-tester": ^8.34.1
    eslint-typegen: ^2.2.0
    jiti: ^2.4.2
    tsdown: ^0.12.8
    tsx: ^4.20.3
    typescript: ^5.8.3
    vitest: ^3.2.4

  peer:
    "@eslint-react/eslint-plugin": ^1.52.2
    "@unocss/eslint-plugin": ^66.2.3
    astro-eslint-parser: ^1.2.2
    eslint: ^9.29.0
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-tailwindcss: ^3.18.0
    prettier-plugin-astro: ^0.14.1
    tailwindcss: 3.4.17
    unocss: ^66.2.3
    vue: ^3.5.17

  prod:
    "@antfu/install-pkg": ^1.1.0
    "@clack/prompts": ^0.11.0
    "@eslint-community/eslint-plugin-eslint-comments": ^4.5.0
    "@eslint/markdown": ^6.5.0
    "@stylistic/eslint-plugin": ^4.4.1
    "@typescript-eslint/eslint-plugin": ^8.34.1
    "@typescript-eslint/parser": ^8.34.1
    "@vitest/eslint-plugin": ^1.2.7
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.0
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^51.0.3
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.20.0
    eslint-plugin-perfectionist: ^4.15.0
    eslint-plugin-pnpm: ^0.3.1
    eslint-plugin-regexp: ^2.9.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^59.0.1
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vue: ^10.2.0
    eslint-plugin-yml: ^1.18.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.2.0
    jsonc-eslint-parser: ^2.4.0
    local-pkg: ^1.1.1
    parse-gitignore: ^2.0.0
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.1.3
    yaml-eslint-parser: ^1.3.0
onlyBuiltDependencies:
  - esbuild
