packages:
  - tests/fixtures/*

strictPeerDependencies: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
engineStrict: true
minimumReleaseAge: 1440 # 1 day

overrides:
  rolldown: 1.0.0-beta.44

catalogs:
  dev:
    "@eslint/config-inspector": 1.3.0
    "@types/node": 22.18.12
    eslint-typegen: 2.3.0
    jiti: 2.6.1
    tsdown: 0.15.9
    typescript: 5.9.3
    vitest: 3.2.4

  peer:
    eslint: 9.38.0

  prod:
    "@antfu/eslint-config": 6.1.0
    eslint-flat-config-utils: 2.1.4

onlyBuiltDependencies:
  - esbuild
