name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: setup node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: lts/*
          cache: pnpm

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint

      - name: typecheck
        run: pnpm typecheck

  test:
    name: "test (os: ${{ matrix.os }}, node: ${{ matrix.node }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [24, 22, 20]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: setup node ${{ matrix.node }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
