name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/reusable-ci.yaml@dc5bd39f7ea1504fb0ff9745fbc65c629178d8b3 # v0.11.2
    permissions:
      contents: read

  test:
    uses: luxass/shared-workflows/.github/workflows/reusable-test.yaml@dc5bd39f7ea1504fb0ff9745fbc65c629178d8b3 # v0.11.2
    permissions:
      contents: read
