name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/ci.yaml@f679de59851660fb23fd7e453ea66b9e76cb55aa # v0.11.0
    permissions:
      contents: read


  test:
    name: "test (node: ${{ matrix.node }}"
    strategy:
      matrix:
        node: [24, 22]
      fail-fast: false
    uses: luxass/shared-workflows/.github/workflows/test.yaml@f679de59851660fb23fd7e453ea66b9e76cb55aa # v0.11.0
    permissions:
      contents: read
