name: Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    uses: luxass/shared-workflows/.github/workflows/reusable-release-npm.yaml@dc5bd39f7ea1504fb0ff9745fbc65c629178d8b3 # v0.11.2
    permissions:
      id-token: write
      contents: write
    with:
      environment: npm-registry
      stage: true
